# Generated by Django 4.2.25 on 2025-11-05 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0005_configuracionenvio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_procesamiento', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('solicitada', 'Solicitada'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('completada', 'Completada')], default='solicitada', max_length=20)),
                ('motivo', models.TextField(blank=True)),
                ('notas_internas', models.TextField(blank=True)),
                ('importe_total_devolucion', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('gastos_envio_devolucion', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devoluciones', to='ventas.pedido')),
            ],
            options={
                'verbose_name': 'devolución',
                'verbose_name_plural': 'devoluciones',
                'ordering': ['-fecha_solicitud'],
            },
        ),
        migrations.CreateModel(
            name='LineaDevolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_devuelta', models.PositiveIntegerField()),
                ('precio_unitario_devolucion', models.DecimalField(decimal_places=2, max_digits=10)),
                ('razon', models.CharField(choices=[('defectuoso', 'Producto defectuoso'), ('no_satisfaccion', 'No satisface expectativas'), ('error_envio', 'Error en el envío'), ('cambio_talla', 'Cambio de talla'), ('otro', 'Otro motivo')], default='no_satisfaccion', max_length=20)),
                ('devolucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='ventas.devolucion')),
                ('linea_pedido_original', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.lineapedido')),
            ],
            options={
                'verbose_name': 'línea de devolución',
                'verbose_name_plural': 'líneas de devolución',
            },
        ),
    ]
