# Generated by Django 4.2.25 on 2025-11-05 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0006_devolucion_lineadevolucion'),
    ]

    operations = [
        migrations.AddField(
            model_name='devolucion',
            name='base_imponible_devolucion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='devolucion',
            name='iva_devolucion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
