# Generated by Django 4.2.25 on 2026-02-23 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0007_devolucion_base_imponible_devolucion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='destinatario_cp',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='pedido',
            name='destinatario_direccion',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='pedido',
            name='destinatario_localidad',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pedido',
            name='destinatario_nombre',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='pedido',
            name='destinatario_provincia',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pedido',
            name='destinatario_telefono',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='pedido',
            name='mensaje_dedicatoria',
            field=models.TextField(blank=True, default=''),
        ),
    ]
