# Generated by Django 4.2.25 on 2025-11-21 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicio',
            options={'ordering': ['categoria', 'titulo'], 'verbose_name': 'servicio', 'verbose_name_plural': 'servicios'},
        ),
        migrations.AddField(
            model_name='servicio',
            name='alergenos',
            field=models.CharField(blank=True, help_text='Alérgenos separados por comas: gluten,huevos,lacteos,...', max_length=200),
        ),
        migrations.AddField(
            model_name='servicio',
            name='categoria',
            field=models.CharField(choices=[('entrantes_picoteo', 'Entrantes y Picoteo'), ('primeros', 'Primeros Platos'), ('segundos', 'Segundos Platos'), ('postres', 'Postres'), ('bebidas', 'Bebidas'), ('reservas', 'Reservas'), ('localizacion', 'Localización'), ('contacto', 'Contacto')], default='entrantes_picoteo', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicio',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='contenido',
            field=models.TextField(max_length=500),
        ),
    ]
