# Generated by Django 4.2.25 on 2025-11-22 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_alter_servicio_options_servicio_alergenos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alergeno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(choices=[('gluten', 'Gluten'), ('crustaceos', 'Crustáceos'), ('huevos', 'Huevos'), ('pescado', 'Pescado'), ('cacahuetes', 'Cacahuetes'), ('soja', 'Soja'), ('lacteos', 'Lácteos'), ('frutos_cascara', 'Frutos de Cáscara'), ('apio', 'Apio'), ('mostaza', 'Mostaza'), ('sesamo', 'Sésamo'), ('sulfitos', 'Sulfitos'), ('altramuces', 'Altramuces'), ('moluscos', 'Moluscos')], max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'alérgeno',
                'verbose_name_plural': 'alérgenos',
            },
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='alergenos',
        ),
        migrations.AddField(
            model_name='servicio',
            name='alergenos',
            field=models.ManyToManyField(blank=True, to='servicios.alergeno'),
        ),
    ]
